ALTER TABLE projects ADD COLUMN IF NOT EXISTS model_type TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS is_guided_tour BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS session_id TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
